apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-deploy
    spec:
      containers:
      - image: 476114152571.dkr.ecr.eu-west-2.amazonaws.com/pythonapp-prac:v1
        name: pythonapp-prac
        resources: {}
status: {}
