apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python-lb-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: python-deploy
  type: LoadBalancer
status:
  loadBalancer: {}